### ISSUE TITLE
InvokableCommandInputAttributeRector generates invalid code.

### ISSUE THREAD

**Issue by mickverm** [rectorphp/rector-symfony#770]
Using:

- `rector/rector` 2.0.16
- `symfony/console` v7.3.0-BETA2

I started with the following command:

```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:hello',
    description: 'Greet the user.',
)]
class HelloCommand extends Command
{
    private const string ARGUMENT_NAME = 'name';

    #[\Override]
    protected function configure(): void
    {
        $this->addArgument(self::ARGUMENT_NAME, InputArgument::OPTIONAL, 'The name of the person to greet.');
    }

    #[\Override]
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $name = $input->getArgument(self::ARGUMENT_NAME);
        $output->writeln("Hello {$name}!");

        return Command::SUCCESS;
    }
}
```

Which returns the following error:

```
[ERROR] Could not process "src\Command\HelloCommand.php" file, due
#0 vendor\rector\rector\vendor\rector\rector-symfony\rules\Symfony73\Rector\Class_\InvokableCommandInputAttributeRector.php(144): Rector\Symfony\Symfony73\NodeAnalyzer\CommandArgumentsAndOptionsResolver->collectCommandArguments()
#1 vendor\rector\rector\src\Rector\AbstractRector.php(112): Rector\Symfony\Symfony73\Rector\Class_\InvokableCommandInputAttributeRector->refactor()
#2 vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(173): Rector\Rector\AbstractRector->enterNode()
#3 vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(90): PhpParser\NodeTraverser->traverseArray()
#4 vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(200): PhpParser\NodeTraverser->traverseNode()
#5 vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(71): PhpParser\NodeTraverser->traverseArray()
#6 vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(49): PhpParser\NodeTraverser->traverse()
#7 vendor\rector\rector\src\Application\FileProcessor.php(95):Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
#8 vendor\rector\rector\src\Application\ApplicationFileProcessor.php(174): Rector\Application\FileProcessor->processFile()
#9 vendor\rector\rector\src\Application\ApplicationFileProcessor.php(151): Rector\Application\ApplicationFileProcessor->processFile()
#10 vendor\rector\rector\src\Application\ApplicationFileProcessor.php(128): Rector\Application\ApplicationFileProcessor->processFiles()
#11 vendor\rector\rector\src\Console\Command\ProcessCommand.php(167): Rector\Application\ApplicationFileProcessor->run()
#12 vendor\rector\rector\vendor\symfony\console\Command\Command.php(285): Rector\Console\Command\ProcessCommand->execute()
#13 vendor\rector\rector\vendor\symfony\console\Application.php(900): RectorPrefix202505\Symfony\Component\Console\Command\Command->run()
#14 vendor\rector\rector\vendor\symfony\console\Application.php(279): RectorPrefix202505\Symfony\Component\Console\Application->doRunCommand()
#15 vendor\rector\rector\src\Console\ConsoleApplication.php(63):RectorPrefix202505\Symfony\Component\Console\Application->doRun()
#16 vendor\rector\rector\vendor\symfony\console\Application.php(162): Rector\Console\ConsoleApplication->doRun()
#17 vendor\rector\rector\bin\rector.php(130): RectorPrefix202505\Symfony\Component\Console\Application->run()
#18 vendor\rector\rector\bin\rector(5): require_once('...')
#19 vendor\bin\rector(119): include('...')
#20 {main}". On line: 30
```

After removing `private const string ARGUMENT_NAME = 'name';` and replacing `self::ARGUMENT_NAME` with `'name'`, Rector produces the following invalid code:

```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Attribute\Command\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;

#[AsCommand(
    name: 'app:hello',
    description: 'Greet the user.',
)]
class HelloCommand
{
    #[\Override]
    protected function __invoke(#[Argument]
    string $name): int
    {
        $output->writeln("Hello {$name}!");
        return Command::SUCCESS;
    }
}
```

Which has the following issues:

- `#[Argument]` has an incorrect using statement: `Symfony\Component\Console\Attribute\Command\Argument` instead of `Symfony\Component\Console\Attribute\Argument`.
- `#[Argument]` lost its description.
- `#[Argument]` is no longer optional (aka not nullable)
- `OutputInterface $output` argument is missing from `__invoke()`
- `[\Override]` was not removed
- `__invoke()` is protected instead of public

**Comment by samsonasik** [comment]
@mickverm could you provide the expected codes for other issues? thank you.

**Comment by mickverm** [comment]
Of course!

```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:hello',
    description: 'Greet the user.',
)]
class HelloCommand
{
    public function __invoke(
        #[Argument(name: 'name', description: 'The name of the person to greet.')]
        ?string $name,
        OutputInterface $output,
    ): int {
        $output->writeln("Hello {$name}!");
        return Command::SUCCESS;
    }
}
```

**Comment by samsonasik** [comment]
I will check when I have a chance, but feel free to create a PR or two to ease to check if you have a chance too :)

**Comment by samsonasik** [comment]
@mickverm that should already resolved now on latest dev-main, Please try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```

If you have another invalid use case, please provide other expected codes, thank you.

**Comment by mickverm** [comment]
@samsonasik thank you for the quick changes, but this still doesn't handle my original case where the argument (or option) name is defined as a constant. That still returns the error I previously mentioned.

```php
private const string ARGUMENT_HOST = 'host';

$this->addArgument(self::ARGUMENT_HOST, InputArgument::OPTIONAL, 'The host to connect to.');
```

I also noticed a new issue:
- The `#[Argument]` attribute doesn't have a named `mode` constructor parameter.

**Comment by samsonasik** [comment]
That seems expected due to clean up Attribute, handle by php-parser printer, we rely on that, that known drawback https://github.com/rectorphp/rector?tab=readme-ov-file#known-drawbacks

**Comment by mickverm** [comment]
That makes sense, thanks for the explanation 😄 keep up the good work!
